language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.drush/cache
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0

before_install:
  - openssl aes-256-cbc -K $encrypted_a13fb9434454_key -iv $encrypted_a13fb9434454_iv -in apikey.enc -out apikey -d

install:
  - composer install

script:
  - composer phpunit

after_success:
  - composer coveralls
  - composer codacy
