language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.drush/cache
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0

install:
  - composer install

script:
  - composer phpunit

after_success:
  - composer coveralls
  - composer codacy
